[package]
authors = ["HAYASAKARyosuke <hayasaka.ryosuke@gmail.com>"]
name = "blinktest"
edition = "2018"
version = "0.1.0"

[dependencies]
panic-halt = "0.2"
wio_terminal = "0.3.0"
embedded-hal = "0.2.4"
